# Generated by Django 4.1.4 on 2022-12-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=50)),
                ('snow_overnight', models.IntegerField(default=0)),
                ('snow_24hrs', models.IntegerField(default=0)),
                ('snow_48hrs', models.IntegerField(default=0)),
                ('snow_72hrs', models.IntegerField(default=0)),
                ('snow_7days', models.IntegerField(default=0)),
                ('snow_30days', models.IntegerField(default=0)),
                ('snow_total', models.IntegerField(default=0)),
                ('snow_bae_depth', models.IntegerField(default=0)),
                ('trails_total', models.IntegerField(default=0)),
                ('trails_open', models.IntegerField(default=0)),
                ('lifts_total', models.IntegerField(default=0)),
                ('lifts_open', models.IntegerField(default=0)),
            ],
        ),
    ]
