# Generated by Django 4.1.4 on 2022-12-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_activerecord_country_activerecord_passes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerecord',
            name='snow_24hrs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_30days',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_48hrs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_72hrs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_7days',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_base_depth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_overnight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_total',
            field=models.FloatField(default=0),
        ),
    ]
