# Generated by Django 4.1.4 on 2022-12-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0004_alter_activerecord_snow_24hrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerecord',
            name='lifts_open',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='lifts_total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_24hrs',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_30days',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_48hrs',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_72hrs',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_7days',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_base_depth',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_overnight',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='snow_total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='trails_open',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activerecord',
            name='trails_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
