# Generated by Django 4.1.4 on 2022-12-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0005_alter_activerecord_lifts_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activerecord',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
