# Generated by Django 4.1.4 on 2022-12-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0006_activerecord_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='activerecord',
            name='reservation',
            field=models.BooleanField(default=False),
        ),
    ]
